baseURL = "https://blog.leanku.com"
title = "Leanku"
paginate = 5
theme = "PaperMod"
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true

[minify]
  disableXML = true

[languages.en]
  languageName = "English"
  weight = 1

[languages.en.taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[[languages.en.menu.main]]
  name = "Archive"
  url = "archives"
  weight = 5

[[languages.en.menu.main]]
  name = "Search"
  url = "search/"
  weight = 10

[[languages.en.menu.main]]
  name = "Tags"
  url = "tags/"
  weight = 10

[[languages.en.menu.main]]
    name = "Rss"
    url = "index.xml"

[[languages.en.menu.main]]
  name = "Home"
  url = "/"
  weight = 2
  title = "Home"

[outputs]
  home = [ "HTML", "RSS", "JSON" ]

[params]
  env = "production"
  description = "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
  author = "Leanku"
  defaultTheme = "dark"
  ShowShareButtons = true
  ShowReadingTime = true
  displayFullLangName = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = false #面包屑
  ShowCodeCopyButtons = true 
  ShowRssButtonInSectionTermList = true
  ShowToc = true
  images = [ "papermod-cover.png" ]
  Copyright = false

  #ICP
  [params.icpRecord]
    enabled = true
    icp = "陕ICP备2022003125号"
    url = "https://beian.miit.gov.cn/"

  [params.assets]
    disableHLJS = true
    favicon16x16 = 'images/favicon-16x16.png'
    favicon32x32 = 'images/favicon-32x32.png'

  [params.profileMode]
    enabled = false
    title = "Leanku"
    imageUrl = "/images/gravatar.jpg"
    imageTitle = "Leanku"

    [[params.profileMode.buttons]]
      name = "Archives"
      url = "archives"

    [[params.profileMode.buttons]]
      name = "Tags"
      url = "tags"

  [params.homeInfoParams]
    # Title = "Cool ~"
    Content = """
[<font style="color: #F55852;font-weight: 400;">渐入佳境</font>](https://) 便是我对人生的最大祝福...
"""

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/leanku"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:https://leanku@foxmail.com"

  [[params.socialIcons]]
    name = 'tea'
    url = 'https://leanku.com'

  [[params.socialIcons]]
    name = "Rss"
    url = "index.xml"

  [params.editPost]
    # URL = "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
    # Text = "Suggest Changes"
    # appendFilePath = true

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  noClasses = true
  lineNos = false
  codeFences = true
  guessSyntax = true
  style = "atom-one-dark"
  #style = "solarized-dark"
  # style = monokai
  tabWidth = 4
  lineNumbersInTable = true

[privacy.vimeo]
  disabled = false
  simple = true

[privacy.twitter]
  disabled = false
  enableDNT = true
  simple = true

[privacy.instagram]
  disabled = false
  simple = true

[privacy.youtube]
  disabled = false
  privacyEnhanced = true

[services.instagram]
  disableInlineCSS = true

[services.twitter]
  disableInlineCSS = true
